name: Deploy ConferenceSystem.Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v4

      - name: .NET 8 kur
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ConferenceSystem.Web/ConferenceSystem.Web.csproj

      - name: Build
        run: dotnet build ConferenceSystem.Web/ConferenceSystem.Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ConferenceSystem.Web/ConferenceSystem.Web.csproj -c Release -o ./publish

      - name: Sunucuda geçici deploy klasörü oluştur
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /var/www/myapp_deploy

      - name: Publish dosyalarını sunucuya kopyala
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "publish/*"
          target: "/var/www/myapp_deploy"

      - name: Canlıya al ve servisi restart et
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /var/www/myapp
            rsync -av --delete \
              --exclude 'appsettings.json' \
              --exclude 'wwwroot/uploads' \
              /var/www/myapp_deploy/publish/ /var/www/myapp/
            systemctl restart myapp.service