// <auto-generated />
using System;
using ConferenceSystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceSystem.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326172307_LowerCaseFix")]
    partial class LowerCaseFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ıspublished");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publishdate");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("actiontype");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entityıd");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entitytype");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ıpaddress");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("performedby");

                    b.HasKey("Id")
                        .HasName("pk_auditlogs");

                    b.ToTable("auditlogs");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.CommitteeMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommitteeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("committeetype");

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("fullname");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ınstitution");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_committeemembers");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ıx_committeemembers_conferenceıd");

                    b.ToTable("committeemembers");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Conference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("location");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("logopath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizingCommitteeInfo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("organizingcommitteeınfo");

                    b.Property<string>("PresidentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("presidentname");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("shortname");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startdate");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("websiteurl");

                    b.HasKey("Id")
                        .HasName("pk_conferences");

                    b.ToTable("conferences");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.ContentPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ıspublished");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("metadescription");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("metatitle");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ıx_pages_slug");

                    b.ToTable("pages");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.EditorialDecision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decidedat");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("decisionnote");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("decisiontype");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionıd");

                    b.HasKey("Id")
                        .HasName("pk_editorialdecisions");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ıx_editorialdecisions_submissionıd");

                    b.ToTable("editorialdecisions");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.HomePageSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<string>("ContactHtml")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contacthtml");

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacttitle");

                    b.Property<string>("HeroBadgeText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("herobadgetext");

                    b.Property<string>("HeroDescription")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("herodescription");

                    b.Property<string>("HeroPrimaryButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("heroprimarybuttontext");

                    b.Property<string>("HeroPrimaryButtonUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("heroprimarybuttonurl");

                    b.Property<string>("HeroSecondaryButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("herosecondarybuttontext");

                    b.Property<string>("HeroSecondaryButtonUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("herosecondarybuttonurl");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("herotitle");

                    b.Property<string>("HighlightBox1Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("highlightbox1title");

                    b.Property<string>("HighlightBox1Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("highlightbox1value");

                    b.Property<string>("HighlightBox2Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("highlightbox2title");

                    b.Property<string>("HighlightBox2Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("highlightbox2value");

                    b.Property<string>("HighlightBox3Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("highlightbox3title");

                    b.Property<string>("HighlightBox3Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("highlightbox3value");

                    b.Property<string>("PosterImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("posterımageurl");

                    b.Property<bool>("ShowAnnouncements")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("showannouncements");

                    b.Property<bool>("ShowCommitteeMembers")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("showcommitteemembers");

                    b.Property<bool>("ShowContact")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("showcontact");

                    b.Property<bool>("ShowImportantDates")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("showımportantdates");

                    b.Property<bool>("ShowRegistrationCategories")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("showregistrationcategories");

                    b.Property<bool>("ShowSpeakers")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("showspeakers");

                    b.HasKey("Id")
                        .HasName("pk_homepagesettings");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ıx_homepagesettings_conferenceıd");

                    b.ToTable("homepagesettings");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.ImportantDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datevalue");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ımportantdates");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ıx_ımportantdates_conferenceıd");

                    b.ToTable("ımportantdates");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.MagicLoginToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresat");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısused");

                    b.Property<long?>("ReviewerId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewerıd");

                    b.Property<long?>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionıd");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("token");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usertype");

                    b.HasKey("Id")
                        .HasName("pk_magiclogintokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ıx_magiclogintokens_token");

                    b.ToTable("magiclogintokens");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.Property<string>("MenuGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("menugroup");

                    b.Property<string>("MenuLocation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("menulocation");

                    b.Property<bool>("OpenInNewTab")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("openınnewtab");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_menuıtems");

                    b.ToTable("menuıtems");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Proceeding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DOI")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("doı");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publishedat");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionıd");

                    b.HasKey("Id")
                        .HasName("pk_proceedings");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ıx_proceedings_submissionıd");

                    b.ToTable("proceedings");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.RegistrationCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("categoryname");

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("fee");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.HasKey("Id")
                        .HasName("pk_registrationcategories");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ıx_registrationcategories_conferenceıd");

                    b.ToTable("registrationcategories");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommentToAuthor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("commenttoauthor");

                    b.Property<string>("CommentToEditor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("commenttoeditor");

                    b.Property<int>("MethodScore")
                        .HasColumnType("int")
                        .HasColumnName("methodscore");

                    b.Property<int>("OriginalityScore")
                        .HasColumnType("int")
                        .HasColumnName("originalityscore");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recommendation");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("int")
                        .HasColumnName("relevancescore");

                    b.Property<long>("ReviewAssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewassignmentıd");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submittedat");

                    b.Property<int>("WritingScore")
                        .HasColumnType("int")
                        .HasColumnName("writingscore");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ReviewAssignmentId")
                        .HasDatabaseName("ıx_reviews_reviewassignmentıd");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.ReviewAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assignedat");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("remindersentat");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewerıd");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionıd");

                    b.HasKey("Id")
                        .HasName("pk_reviewassignments");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ıx_reviewassignments_reviewerıd");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ıx_reviewassignments_submissionıd");

                    b.ToTable("reviewassignments");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Reviewer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("expertise");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.HasKey("Id")
                        .HasName("pk_reviewers");

                    b.ToTable("reviewers");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.RevisionFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("filepath");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionıd");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploadedat");

                    b.HasKey("Id")
                        .HasName("pk_revisionfiles");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ıx_revisionfiles_submissionıd");

                    b.ToTable("revisionfiles");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChairName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("chairname");

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endtime");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("room");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starttime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ıx_sessions_conferenceıd");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.SessionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<int>("PresentationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("presentationminutes");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("sessionıd");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submissionıd");

                    b.HasKey("Id")
                        .HasName("pk_sessionıtems");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ıx_sessionıtems_sessionıd");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ıx_sessionıtems_submissionıd");

                    b.ToTable("sessionıtems");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.SiteSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_sitesettings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ıx_sitesettings_key");

                    b.ToTable("sitesettings");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.SmtpSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fromemail");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fromname");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("host");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<bool>("RequireAuthentication")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requireauthentication");

                    b.Property<string>("SecurityMode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("securitymode");

                    b.Property<int>("TimeoutMilliseconds")
                        .HasColumnType("int")
                        .HasColumnName("timeoutmilliseconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedat");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("usessl");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_smtpsettings");

                    b.ToTable("smtpsettings");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Speaker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bio");

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("fullname");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("ımageurl");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ınstitution");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ısactive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_speakers");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ıx_speakers_conferenceıd");

                    b.ToTable("speakers");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ıd");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AbstractText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abstracttext");

                    b.Property<string>("AuthorFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("authorfullname");

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("conferenceıd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("filepath");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ınstitution");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("keywords");

                    b.Property<DateTime?>("RevisionReminderSentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revisionremindersentat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("submissionnumber");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("ConferenceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ıx_submissions_conferenceıd_email");

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.CommitteeMember", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_committeemembers_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.EditorialDecision", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editorialdecisions_submissions_submissionıd");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.HomePageSetting", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homepagesettings_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.ImportantDate", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ımportantdates_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Proceeding", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proceedings_submissions_submissionıd");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.RegistrationCategory", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registrationcategories_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Review", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.ReviewAssignment", "ReviewAssignment")
                        .WithMany()
                        .HasForeignKey("ReviewAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_reviewassignments_reviewassignmentıd");

                    b.Navigation("ReviewAssignment");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.ReviewAssignment", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Reviewer", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewassignments_reviewers_reviewerıd");

                    b.HasOne("ConferenceSystem.Web.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewassignments_submissions_submissionıd");

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.RevisionFile", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revisionfiles_submissions_submissionıd");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Session", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.SessionItem", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Session", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessionıtems_sessions_sessionıd");

                    b.HasOne("ConferenceSystem.Web.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessionıtems_submissions_submissionıd");

                    b.Navigation("Session");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Speaker", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_speakers_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Submission", b =>
                {
                    b.HasOne("ConferenceSystem.Web.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_conferences_conferenceıd");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceSystem.Web.Entities.Session", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
